/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Coche(private var _marca: String = "Ford", private var _modelo: Int = 2020) {
    var marca: String
        get() = _marca
        set(value) {
            _marca = value
        }
    var modelo: Int
        get() = _modelo
        set(value) {
            _modelo = value
        }
}
interface Perimetrable {
    fun calcularPerimetro(): Double
}


class Rectangulo(val ancho: Double, val alto: Double) : Perimetrable {
    var area: Double

    // El bloque init se usa para inicializar propiedades o ejecutar código en la creación.
    init {
        // 'area' se calcula una vez cuando se crea el objeto.
        area = ancho * alto
        println("Se ha creado un rectángulo de $ancho x $alto con un área de $area")
    }

    // Un método de la clase
    fun describir() {
        println("Este es un rectángulo.")
    }

    // Un método que realiza un cálculo
    override fun calcularPerimetro(): Double {
        return 2 * (ancho + alto)
    }
}

class Circulo(val radio: Double) : Perimetrable {
    var area: Double

    // El bloque init se usa para inicializar propiedades o ejecutar código en la creación.
    init {
        // 'area' se calcula una vez cuando se crea el objeto.
        area = radio * radio * Math.PI
        println("Se ha creado un Circulo de radio $radio con un área de $area")
    }

    // Un método de la clase
    fun describir() {
        println("Este es un Circulo.")
    }

    // Un método que realiza un cálculo
    override fun calcularPerimetro(): Double {
        return 2 * Math.PI * radio
    }
}

fun main() {

    val coche = Coche("Chevrolet", 2025)
    val rectangulo = Rectangulo(10.0, 5.0)
    val circulo = Circulo(10.0)

    println("Marca ${coche.marca}")
    println("Modelo ${coche.modelo}")
    println("Área ${rectangulo.area}")
    println("Perímetro ${rectangulo.calcularPerimetro()}")
    println("Área ${circulo.area}")
    println("Perímetro ${circulo.calcularPerimetro()}")
    
    val figuras: List<Perimetrable> = listOf(rectangulo, circulo)
    for (figura in figuras) {
        println("Perímetro del ${figura.javaClass.simpleName}: ${figura.calcularPerimetro()}")
    }


}
